
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async readFolder(path: string) : Promise<Result<FileEntry[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCanonicalPath(path: string) : Promise<Result<string, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_canonical_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrackData(pathString: string, refresh: boolean | null) : Promise<Result<FileEntry, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_track_data", { pathString, refresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTracksData(paths: string[], refresh: boolean | null) : Promise<Result<FileEntry[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tracks_data", { paths, refresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFolderTrackPaths(path: string, deep: boolean | null) : Promise<Result<string[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folder_track_paths", { path, deep }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async controlPlayback(action: StreamAction) : Promise<Result<StreamStatus, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("control_playback", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOutputDevices() : Promise<Result<AudioDeviceInfo[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWaveform(path: string, binSize: number) : Promise<Result<number[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_waveform", { path, binSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLastfmAuth() : Promise<Result<string, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_lastfm_auth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeLastfmAuth(token: string) : Promise<Result<string, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_lastfm_auth", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeLastfmAccount() : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_lastfm_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scrobbleTrack(scrobble: SerializedScrobble) : Promise<Result<SerializedScrobbleResponse, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scrobble_track", { scrobble }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async processOfflineScrobbles(scrobbles: SerializedOfflineScrobble[]) : Promise<Result<SerializedScrobbleResponse, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("process_offline_scrobbles", { scrobbles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNowPlaying(scrobble: SerializedScrobble) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_now_playing", { scrobble }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastfmAuthStatus() : Promise<Result<boolean, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_lastfm_auth_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastfmProfile() : Promise<Result<string, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_lastfm_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastfmPlayCount(title: string, artist: string, username: string) : Promise<Result<PlayCountResponse | null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_lastfm_play_count", { title, artist, username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeId3Frames(filePath: string, targetTag: TagTypeArg, args: FrameArgs[]) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_id3_frames", { filePath, targetTag, args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Materialize File Provider placeholders, emitting progress per path until
 * every one reaches a terminal state. Callers wanting fire-and-forget simply
 * don't await the invoke promise.
 */
async downloadTracks(paths: string[]) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_tracks", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AudioDeviceInfo = { name: string; is_default: boolean }
export type DownloadStatus = 
/**
 * Fully present on disk, or on a platform/volume without a File Provider.
 */
"Local" | "NotDownloaded" | "Downloading" | "DownloadFailed"
export type Error = { type: "Audio"; data: string } | { type: "Backend"; data: string } | { type: "Id3"; data: string } | { type: "FileSystem"; data: string } | { type: "LastFm"; data: string } | { type: "Waveform"; data: string } | { type: "Sql"; data: string } | { type: "Store"; data: string } | { type: "Stronghold"; data: string } | { type: "Other"; data: string }
export type FileEntry = { path: string; name: string; filename: string; tags: Partial<{ [key in string]: string }>; thumbnail_uri: string; full_uri: string; is_playlist_track: boolean; valid: boolean; primary_tag: TagTypeArg | null; extension: string; duration: number; play_count: number; date_added: string | null; last_played: string | null; download_status: DownloadStatus }
export type FrameArgs = { frame: string; value: string }
export type PlayCountResponse = { track: Track }
export type SerializedOfflineScrobble = { scrobble: SerializedScrobble; timestamp: number }
export type SerializedScrobble = { artist: string; track: string; album: string | null; track_number: number | null; duration: number; album_artist: string | null }
export type SerializedScrobbleResponse = { accepted: number; ignored: number }
export type StreamAction = { Play: string } | "Pause" | "Resume" | { Seek: number } | { SetLoop: boolean } | { SetVolume: number } | "ToggleMute" | "Reset" | { SetOutputDevice: string | null } | 
/**
 * Query-only: returns current state without changing anything. Since
 * this round-trips through the same channel the audio thread's startup
 * logic runs on before it starts servicing requests, the response is
 * guaranteed to reflect e.g. a startup device fallback already applied
 * on this thread — unlike a fire-and-forget event, which can fire before
 * a listener has been registered.
 */
"GetStatus"
export type StreamStatus = { is_playing: boolean; position: number; duration: number; is_looping: boolean; path: string | null; volume: number; is_muted: boolean; 
/**
 * The currently-active output device, or `None` for the system default.
 * Authoritative: only ever set to the device that's actually in use.
 * `#[serde(default)]` so playback state persisted before this field
 * existed still deserializes instead of being discarded wholesale.
 */
output_device?: string | null }
export type TagTypeArg = "id3v2.2" | "id3v2.3" | "id3v2.4"
export type Track = { playcount: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
